### ISSUE TITLE
Using Graph-Based Models for Prediction

### ISSUE THREAD

**Issue by ssakhavi** [khalil-research/PyEPO#24]
Hi, 

Thank you for the great repo!
Is it possible to use GNNs as the model?
For example, can we use a PyG model?

Such as the paper below?
https://arxiv.org/pdf/2302.05636.pdf
![image](https://github.com/khalil-research/PyEPO/assets/6030203/8b7b27b2-3ca5-4503-aef3-b539ed7a63ca)

**Comment by LucasBoTang** [comment]
Hi @ssakhavi ,

Thank you for the kind words about the repository!

Given that PyEPO is built on PyTorch, it should be indeed compatible with PyTorch Geometric (PyG).

However, it's important to note that while theoretically, the compatibility between PyEPO and PyG should allow for the integration of PyG models within the PyEPO framework, this integration has not been explicitly tested in practice. I would like to see the use between PyG and PyEPO, and glad to contribute towards bridging any existing gaps.

Best regards,

Bo

**Comment by ssakhavi** [comment]
@LucasBoTang Sorry for the late reply. 


Thank you. 
We'll consider this library when narrowing down our possible options.
