### ISSUE TITLE
About Constrainted Deep modeling

### ISSUE THREAD

**Issue by xtzd** [khalil-research/PyEPO#4]
Hi, I am new to this repo. I wonder if the PyEPO could solve such work:

a simple multi-demensional regression supervised deep learning problem. 

suppose **x** : (x1,x2,x3,...xm)
suppose **y** : (y1,y2,y3,...yn)

**y_pred** = NeuralNetwork(**x**)
and we want to minimize 

loss(**y_pred**,**y_true**)

 under a linear inequality constraint **R** ,such as 

a*y1+b*y2+...n*yn<A

We want to train the Network.

Can PyEPO solve such problem? If it could, could you provide simple paradigm?
Thank you!

**Comment by LucasBoTang** [comment]
Hi xztd,

PyEPO is not suitable for your problem. It is designed to deal with optimization problems with unknown cost coefficients. Here you want to predict a solution with a linear inequality constraint directly.
