### ISSUE TITLE
Memory leak caused by gurobipy

### ISSUE THREAD

**Issue by Tianyuan-Zhang** [khalil-research/PyEPO#44]
When running the third tutorial notebook (03 Training and Testing: Train and test different approaches) with python=3.12,
there is a memory leak caused by gurobipy (reported here: https://support.gurobi.com/hc/en-us/articles/27635574446353-Memory-leak-in-gurobipy-with-Python-3-12).
Switch to python=3.11 can solve the memory leak problem.
It's better to restrict the python version when installing pyepo.

**Comment by LucasBoTang** [comment]
Thank you so much for bringing this to my attention! I’ve already added a restriction to the Python version. Your feedback is greatly appreciated!

**Comment by LucasBoTang** [comment]
Hi, the problem is solved on Gurobi 12.0.0.
