### ISSUE TITLE
Notebook example on portfolio optimization

### ISSUE THREAD

**Issue by jackliu333** [khalil-research/PyEPO#6]
Can add an example on portfolio optimization also?

**Comment by LucasBoTang** [comment]
We do not currently have plans for that, but you are welcome to provide relevant data and models。

**Comment by LucasBoTang** [comment]
Hi @jackliu333 ,

We have added [portfolio synthetic dataset](https://github.com/khalil-research/PyEPO/blob/main/pkg/pyepo/data/portfolio.py)  and [Gurobi model](https://github.com/khalil-research/PyEPO/blob/main/pkg/pyepo/model/grb/portfolio.py).

**Comment by jackliu333** [comment]
Thanks! This is very helpful.
