### ISSUE TITLE
Negative costs

### ISSUE THREAD

**Issue by jackliu333** [khalil-research/PyEPO#7]
The SPO+ loss function has a term 2*pred_cost - real_cost. It seems an error will throw up when 2*pred_cost < real_cost for a given edge. Is there any control over this potential issue? Or is it already handled in the codes?

**Comment by LucasBoTang** [comment]
Hi Jack,
Sorry for the late response. It is a good question. Negative cost may make the optimization model wrong, and further cause crashes or unknown issues.  Therefore, you should be careful in your formulation. For example, I add the extra upper bound (1) to avoid the unbounded case in the shortest path.
In short, you need some additional action to handle this issue. 
In addition, the paper "[Learning with Combinatorial Optimization Layers: a Probabilistic Approach"](https://arxiv.org/abs/2207.13513) provides a multiplicative method that resolves this issue.
